version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - mongo
    image: infisical/backend
    environment:
      - ENCRYPTION_KEY
      - JWT_SIGNUP_SECRET
      - JWT_REFRESH_SECRET
      - JWT_AUTH_SECRET
      - JWT_SERVICE_SECRET
      - JWT_PROVIDER_AUTH_SECRET
      - JWT_AUTH_LIFETIME
      - JWT_REFRESH_LIFETIME
      - JWT_SIGNUP_LIFETIME
      - JWT_PROVIDER_AUTH_LIFETIME
      - MONGO_URL
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - SITE_URL
    networks:
      - infisical

  frontend:
    container_name: infisical-frontend
    restart: unless-stopped
    depends_on:
      - backend
    image: infisical/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infisical-frontend.rule=Host(`infisical.kantanao.com`)"
      - "traefik.http.services.infisical-frontend.loadbalancer.server.port=3000"
    networks:
      - infisical

  mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - infisical

volumes:
  mongo-data:
    driver: local

networks:
  infisical:
